services:
  db:
    image: postgres:15-alpine
    container_name: url_shortner_db
    restart: always
    environment:
      POSTGRES_DB: url_shortner_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - "55432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: